### ISSUE TITLE
API call to retrieve all listing that have a Listing type = Widget

### ISSUE THREAD

**Issue by tonyalletag** [aml-development/ozp-backend#102]
This is in support of ozp-webtop issue [#651](https://github.com/ozone-development/ozp-webtop/issues/651)

We need an API call that returns all widgets. Listing types that are widgets are expected to be compatible in the webtop

**Comment by mannyrivera2010** [comment]
The api call is http://{host}:8080/api/listings/search/?search=&offset=0&limit=24&type=widget

@SOAP1914

**Comment by clarkjefcoat** [comment]
The call we want is a call that retrieves all of a user's bookmarked listings that are of type widget.

**Comment by mannyrivera2010** [comment]
/api/self/library?type=widget

**Comment by tdressel** [comment]
Passed on latest.

**Comment by SOAP1914** [comment]
I coming back to this next week @tdressel @mannyrivera2010
