### ISSUE TITLE
Search - Categories on left should be alphabetical

### ISSUE THREAD

**Issue by clarkjefcoat** [aml-development/ozp-backend#111]
@clarkjefcoat commented on [Tue Mar 15 2016](https://github.com/ozone-development/ozp-center/issues/541)

To test this:
1.  Log in as an admin
2.  Go to "Center Settings" and add a new category
3.  Go back to main Center page

Expected Result:
Categories should be alphabetical

Actual Result:
New Category is shown at the bottom.

---

@clarkjefcoat commented on [Wed Mar 16 2016](https://github.com/ozone-development/ozp-center/issues/541#issuecomment-197411375)

I will check to see if this is better solved by a python change.

**Comment by tdressel** [comment]
Passed on Latest

**Comment by tdressel** [comment]
Passed on Staging.
