### ISSUE TITLE
Center - New Arrivals shows oldest instead of newest

### ISSUE THREAD

**Issue by clarkjefcoat** [aml-development/ozp-backend#115]
@clarkjefcoat commented on [Sun Mar 20 2016](https://github.com/ozone-development/ozp-center/issues/551)

On the main page "New Arrivals" shows the oldest listing when it should be showing the newest listings.

To test this submit and approve a new listing.  It will not show up under "New Arrivals".  Check the approval date of the listing under "New Arrivals"  You will find that they are old.

**Comment by tdressel** [comment]
Passed on Latest

**Comment by tdressel** [comment]
Passed on Staging in  IE10, FF 31 and Chrome 36.
