### ISSUE TITLE
Create/Edit Page - Changing the security marking

### ISSUE THREAD

**Issue by clarkjefcoat** [aml-development/ozp-backend#123]
@clarkjefcoat commented on [Tue Mar 22 2016](https://github.com/ozone-development/ozp-center/issues/556)

Changes to the security marking of images are not saved unless you also save an image.

To test, edit an existing listing, change the security marking on an image, then save.
Reload the page, your changes will not have saved.

**Comment by tdressel** [comment]
Passed on Latest.
