### ISSUE TITLE
Center Settings - Names in the Stewards tab should be alphabetized

### ISSUE THREAD

**Issue by clarkjefcoat** [aml-development/ozp-backend#130]
@clarkjefcoat commented on [Fri Mar 25 2016](https://github.com/ozone-development/ozp-center/issues/570)

**Comment by tdressel** [comment]
Passed on Latest
Steps used to verify:
Log on as admin
Go to Menu | Center Settings | Stewards Tab
RESULTS - All users were listed in alphabetical order.

**Comment by tdressel** [comment]
Passed on Staging in IE 10, FF 31 and Chrome 36
