### ISSUE TITLE
Allow dashes in the user's DN

### ISSUE THREAD

**Issue by clarkjefcoat** [aml-development/ozp-backend#131]
Even if we start using memcached this will still be safe:
http://stackoverflow.com/questions/5826768/can-memcached-keys-contain-spaces

**Comment by clarkjefcoat** [comment]
The current implementation of utils.make_keysafe is breaking the login for people with hyphenated names and member's of orgs that put hyphens in their DNs.

**Comment by tdressel** [comment]
Needs testing on HS.  Search metrics for user with - in their DN.
