### ISSUE TITLE
Quickview Modal - Admin tab contains extra "modified" record

### ISSUE THREAD

**Issue by akonsowski** [aml-development/ozp-backend#140]
@clarkjefcoat commented on [Fri Mar 25 2016](https://github.com/ozone-development/ozp-center/issues/568)

After a user submits a listing, the Quickview Administration tab contains:

![modifiedsubmitted](https://cloud.githubusercontent.com/assets/7015118/14045742/06b12904-f273-11e5-895b-853d22d1f5b0.png)

There is no need for the "modified" line.  This differs from how the old system recoreded changes.

**Comment by tdressel** [comment]
Passed on latest.

**Comment by tdressel** [comment]
Passed on Staging IE 10, FF 31 and Chrome 36
