### ISSUE TITLE
api/library is not checking if applications are disabled

### ISSUE THREAD

**Issue by akonsowski** [aml-development/ozp-backend#144]
If an application becomes disabled the user should not see the application on its HUD
If the application becomes enabled again the user should not have to re-bookmark the application to view it on their HUD.
refrence to [#150](https://github.com/ozone-development/ozp-hud/issues/150)

**Comment by tdressel** [comment]
Bookmarked an app
Disabled the app.
While still bookmarked and disabled the app does not display in HUD(Homepage), Center(Search results)  or Webtop (open in dashboard)
Enabled again and they show in HUD, Center and Webtop.
PASSED
