### ISSUE TITLE
Bookmarking a disabled app causes problems.

### ISSUE THREAD

**Issue by tdressel** [aml-development/ozp-backend#154]
STR-
1. Disabled an app
2. Refresh screen
3. Go to Listing Management | List View
4. Search for the app and open it
5. Bookmark it
6. Refresh screen
7. Repeat steps 2-5 
8. Enable the app 
9. Go to HUD, Canter and Webtop
RESULTS - App displays twice in HUD and Webtop.
EXPECTED RESULTS - Should save the bookmark so the user doesnt have to keep bookmarking it....causing it to show numerous times in HUD and Webtop.

**Comment by mannyrivera2010** [comment]
@rkenyon1969

**Comment by mannyrivera2010** [comment]
````
POST /api/self/library/ HTTP/1.1
Host: 127.0.0.1:8001
Authorization: Basic YmlnYnJvdGhlcjpwYXNzd29yZA==
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: d6d4436c-cec1-616b-80cc-9999fb014ea9

{
  "listing": {
    "id": 13
  }
}
````
**Response**
````
STATUS: 400 BAD REQUEST
{
  "non_field_errors": [
    "Can not bookmark apps that are disabled"
  ]
}
````

**Comment by mannyrivera2010** [comment]
This ticket will require another ozp-center ticket

**Comment by tdressel** [comment]
Passed on latest.

**Comment by tdressel** [comment]
Failed on HS for me but passed on LS.  @clarkjefcoat will verify.

**Comment by tdressel** [comment]
Passed on Staging.  Does not allow users to bookmark while disabled.  When app is enabled and bookmarked it displays on HUD and Center and allows bookmark to toggle.
