### ISSUE TITLE
Tailored Views - Ability to hide user identities

### ISSUE THREAD

**Issue by clarkjefcoat** [aml-development/ozp-backend#201]
Any end-point that returns user identities should provide the ability to mask or hide usernames.  The decision whether to hide username will be made based on the identity of the logged in user.

**Comment by clarkjefcoat** [comment]
This decision can be made in the access_control plugin.  At a minimum the endpoints for listing owner, contacts and reviews should call this plugin to determine if usernames should be hidden.

**Comment by mannyrivera2010** [comment]
Endpoints with identifiable data:
* listings
* notifications
* profile
* storefront

access_control plugin a new method was created.
````python
def anonymize_identifiable_data(self, username):
     """
    Anonymize Identifiable Data for certain users

    Return:
        True - Anonymize Identifiable Data
        False - Access to see Identifiable Data
    """
    # business logic
    return False
````

**Comment by tdressel** [comment]
Passed on Staging IE 10, FF 31 and Chrome 36
