### ISSUE TITLE
Backend should not dismiss notifications, remove functionality and leave dismissal to frontend.

### ISSUE THREAD

**Issue by wski** [aml-development/ozp-backend#202]

**Comment by tdressel** [comment]
STR:
Share a folder with another user ( add a notification)
Log on as other user
Go to Notifications
(open Dev Tools)
Ignore and Add Folder
Choose Add Folder
RESULTS - Dev Tools | Network Tab | Delete call does not error out anymore.
Repeat and Choose Ignore
RESULTS - Dev Tools | Network Tab | Delete call does not error out anymore.

PASSED ON LATEST

**Comment by tdressel** [comment]
Passed on Staging.  IE10, FF 31 and Chrome 36
