### ISSUE TITLE
Tailored Views - Make hidden identity dynamic 

### ISSUE THREAD

**Issue by mannyrivera2010** [aml-development/ozp-backend#208]
This issue is related to issue #201. The constant value was hard coded.  
The goal of this issue is to put the value in settings.py file for ease of change

**Comment by mannyrivera2010** [comment]
Added a new function in the access control function
````python
def anonymize_value(self, metadata):
    """
    Anonymize Identifiable Value
    Return:
        String Value - Masked Value
    """
    return 'Masked Value'
````

**Comment by tdressel** [comment]
Passed on Staging. IE10, FF 31 and Chrome 36
