### ISSUE TITLE
2PI- Prohibit 2PI users from Submitting/Editing/Owning a Listing.

### ISSUE THREAD

**Issue by tdressel** [aml-development/ozp-backend#215]
2PI- Prohibit 2PI users from Submitting/Editing/Deleting/Owning a Listing on the backend.

Areas that need to be checked.

Log on as 2PI User:

Test 1
Go to Menu 
EXPECTED RESULTS - User should not have Submit Listing, Developer Resources and Listing Management Option. 

Test 2
Go to App Listing | Quick View Details 
EXPECTED RESULTS - Edit icon is not available.

Test 3
Log in as admin
Edit an existing app and submit a new app listing
Each time attempt to add a 2PI user as an APP OWNER
EXPECTED RESULTS- Should give error prohibiting the 2PI owner form being added as app listing owner.

**Comment by mannyrivera2010** [comment]
#221 issue was a duplicate - Tailored Views - 2PI User can't be a listing Owner

**Comment by mannyrivera2010** [comment]
Test 1 and Test 2 are front end changes

**Comment by tdressel** [comment]
Passed on Staging.

**Comment by tdressel** [comment]
Passed on Staging.
