### ISSUE TITLE
Private apps - data base field

### ISSUE THREAD

**Issue by skhtet** [aml-development/ozp-backend#218]
Private apps will allow applications to be private to the organization the application belongs to. i.e., a private application submitted by ORG A will not be visible to users from ORG B.

A field determining whether an application is private or public needs to be added to the database. So a check can be made against a user's organization affiliation and decide whether or not to show the application to said user.

**Comment by mannyrivera2010** [comment]
There is already a field in the model (database) that will meet requirements
````python
class Listing(models.Model):
    ....
    # private listings can only be viewed by members of the same agency
    is_private = models.BooleanField(default=False)
    ....
````
