### ISSUE TITLE
Center->Settings->Organizations

### ISSUE THREAD

**Issue by arw180** [aml-development/ozp-backend#27]
Backend endpoints to support Center Organizations CRUD page

Current endpoints:
* `GET api/agency?cmd=get-records&limit=100&offset=0`
* `POST api/agency`. data = basic Agency data
* `PUT api/agency/<id>`. data = (same as POST)
* `DELETE api/agency/<id>`
* `POST api/image`. data = `{"content_type": "image/png", ...}` - needs to return the image id (not uuid)

NOTE: images are not currently used with Organizations

**Comment by arw180** [comment]
Backend complete

**Comment by tdressel** [comment]
Added, Edited and Deleted an Organization successfully on Latest.

**Comment by tdressel** [comment]
Passed on Staging.
