### ISSUE TITLE
Add profile search endpoint

### ISSUE THREAD

**Issue by arw180** [aml-development/ozp-backend#55]
Submit listing page requires an endpoint like:
`GET api/profile?usernameStartsWith=b`

Should return standard profile info

**Comment by arw180** [comment]
changed query param to `username_starts_with`

**Comment by arw180** [comment]
Backend complete

**Comment by tdressel** [comment]
Passed using https://ci-latest.amlng.di2e.net/api/profile/?username_starts_with=b

**Comment by tdressel** [comment]
Passed on Staging.
